P=pointer_hatsize
objects= 
CFLAGS = `pkg-config --cflags glib-2.0` -g -Wall -std=gnu99 \
            -O0 -fprofile-arcs -ftest-coverage
LDLIBS = `pkg-config --libs glib-2.0`
CC=clang

$(P):$(objects)
